import type { Metadata } from "next";
import Link from "next/link";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav style={{ textAlign: 'center', paddingTop: '20px' }}>
          <h1 style={{ marginBottom: '20px' }}>F1_STATS DASHBOARD</h1>
          <div style={{ display: 'flex', justifyContent: 'space-around' }}>
            <Link href="/drivers" style={{ textDecoration: 'none' }}>Driver List</Link>
            <Link href="/positions" style={{ textDecoration: 'none' }}>Driver Positions</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}

